<?php

namespace EntiteBundle\Repository;

/**
 * CommentaireBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireBRepository extends \Doctrine\ORM\EntityRepository
{
}
