<?php

namespace EntiteBundle\Repository;


/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchByName($nom){
        $q=$this->getEntityManager()
            ->createQuery("select et from EntiteBundle:Etablissement et WHERE et.nom LIKE :nom ")
            ->setParameter(":nom",'%'.$nom.'%');
        return $q->getResult();
    }
}
