<?php

namespace EntiteBundle\Repository;

/**
 * EvenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementsRepository extends \Doctrine\ORM\EntityRepository
{
}
