<?php

namespace EntiteBundle\Repository;

/**
 * RevueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevueRepository extends \Doctrine\ORM\EntityRepository
{
}
