<?php

namespace EvenementBundle\Repository;

/**
 * CommentaireERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireERepository extends \Doctrine\ORM\EntityRepository
{
}
